colocados = ('Palmeiras', 'Santos', 'São Paulo', 'Corinthians', 'Flamengo','Fluminense', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'Chapecoense', 'Ceará', 'Internacional', 'Bahia', 'Vasco da Gama', 'Goiás', 'Coritiba', 'Botafogo', 'Atlético-GO', 'Cuiabá', 'Grêmio')
print(colocados[0:5])
print(colocados[-4:])
print(sorted(colocados))
n1 = colocados.index('Chapecoense')
print(f'Chapecoense esta em {n1 + 1}ª lugar')